server:
  port: 8082
  servlet:
    session:
      cookie:
        name: OAUTH2-CLIENT-SESSIONID
oauth2-server-url: http://localhost:8081
spring:
  application:
    name: oauth2-client
security:
  oauth2:
    client:
      client-id: testClientId
      client-secret: test123456
      user-authorization-uri: ${oauth2-server-url}/oauth/authorize
      access-token-uri: ${oauth2-server-url}/oauth/token
    resource:
      jwt:
        key-uri: ${oauth2-server-url}/oauth/token_key